### Visit page
GET http://localhost:3000/

### Get object by ID
GET http://localhost:3000/api/<id>

### Get all objects
GET http://localhost:3000/api

### Post object
POST http://localhost:3000/api
Content-Type: application/json

{
    TODO: Example post
}

### Update object
PUT http://localhost:3000/api/<id>
Content-Type: application/json

{
    TODO: Example PUT
}

### Delete object by ID
DELETE http://localhost:3000/api/<id>

### Delete all objects
DELETE http://localhost:3000/api