### Get object by ID
GET http://localhost:3000/api/cats/id/abys

### Get all objects
GET http://localhost:3000/api/cats

### Get all endpoints
GET http://localhost:3000/api/cats/endpoints

### Post object
POST http://localhost:3000/api/cats
Content-Type: application/json

  {
    "weight": "3 - 5",
    "name": "Abyssinian",
    "origin": "Egypt",
    "description": "The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.",
    "life_span": "14 - 15",
    "adaptability": 5,
    "affection_level": 5,
    "energy_level": 5,
    "grooming": 1,
    "health_issues": 2,
    "intelligence": 5,
    "image": "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg"
  }

### Update object
PUT http://localhost:3000/api/cats/abys
Content-Type: application/json

  {
    "weight": "3 - 5",
    "name": "Abyssinian",
    "origin": "Egypt",
    "description": "The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.",
    "life_span": "25 - 30",
    "adaptability": 5,
    "affection_level": 5,
    "energy_level": 5,
    "grooming": 1,
    "health_issues": 2,
    "intelligence": 5,
    "image": "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg"
  }

### Delete object by ID
DELETE http://localhost:3000/api/cats/id/<id>

### Delete all objects
DELETE http://localhost:3000/api/cats