### Visit page
GET http://localhost:3000/

### Get object by ID
GET http://localhost:3000/api/cats/id/<id>

### Get all objects
GET http://localhost:3000/api/cats

### Post object
POST http://localhost:3000/api/cats
Content-Type: application/json

{
    TODO: Example post
}

### Update object
PUT http://localhost:3000/api/cats/<id>
Content-Type: application/json

{
    TODO: Example PUT
}

### Delete object by ID
DELETE http://localhost:3000/api/cats/id/<id>

### Delete all objects
DELETE http://localhost:3000/api/cats